### PR TITLE
use iffy action & nim binaries

### PR DESCRIPTION
**Pull request by melMass**
remove caching

### CODE REVIEW

**Comment by melMass** [comment]
arm still needs to be built from source 😢 , but tbh it would be great to have them added to https://github.com/nim-lang/nightlies/releases

There is actually and issue https://github.com/nim-lang/nightlies/issues/84 and a PR for it https://github.com/nim-lang/nightlies/pull/82 by you :)

**Comment by melMass** [comment]
I think it just failed due to rate limits.

**edit:** and the devel build from source now, I didn't find a pattern to get binary devel so I used that in my ci:
https://github.com/melMass/nim-docset/blob/8a0837dca1ba5ac57f4ad403331ca067de693440/.github/workflows/release.yml#L6-L9

**Comment by melMass** [comment]
I think I found it, we can try in this PR if you want, I think it's `latest-devel`, it's the tag name at least: https://github.com/nim-lang/nightlies/releases/tag/latest-devel

**Comment by melMass** [comment]
Yay!

**Comment by ringabout** [comment]
Sweet, thank you very much!

**Pull request merged**
